# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  nodes = [
    {name: "mgr1", ip: "192.168.56.10"},
    {name: "wrk1", ip: "192.168.56.11"},
    {name: "wrk2", ip: "192.168.56.12"},
  ]

  # for each node in the nodes list
  nodes.each do |node| 

    # define each node as Vargrant ref 'n'
    config.vm.define node[:name] do |n|
      
      n.vm.box = "ubuntu/focal64"
      n.vm.hostname = node[:name]
      n.vm.network "private_network", ip: node[:ip]

      n.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "2"
        # make sure cable connected is checked to avoid potential error with SSH auth
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      end
	  
      if node[:name] != "mgr1" 
        # vbox host machine port 8080 -> vm port 80
        n.vm.network "forwarded_port", guest: 80, host: 8080
      end
     
      n.vm.provision "docker" do |d|
        if node[:name] == "mgr1"
          d.post_install_provision "shell", inline:
            "docker swarm init --advertise-addr 192.168.56.10:2377 --listen-addr 192.168.56.10:2377 &&
            echo '------ WORKER TOKEN ------' >> /vagrant/tokens.txt &&
            eval echo $(docker swarm join-token worker) >> /vagrant/tokens.txt &&
            echo -e '\n------ MANAGER TOKEN ------' >> /vagrant/tokens.txt &&
            eval echo $(docker swarm join-token manager) >> /vagrant/tokens.txt"
        end
      end
    end
  end
end
